base_model: NousResearch/Meta-Llama-3-8B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

chat_template: llama3
datasets:
dataset_prepared_path:
val_set_size: 0.05
output_dir: miner_id_24

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true
trust_remote_code: true

adapter: lora
lora_model_dir:
lora_r: 64
lora_alpha: 128
lora_dropout: 0.1
lora_target_linear: true
lora_fan_in_fan_out:

gradient_accumulation_steps: 8
micro_batch_size: 32
num_epochs: 1
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: true
bf16: true
fp16: false
tf32: true

gradient_checkpointing: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 25
xformers_attention: false
flash_attention: true
s2_attention:

wandb_project: Gradients-On-Demand
wandb_entity:
wandb_mode: online
wandb_run: your_name
wandb_runid: default

hub_model_id:
hub_repo:
hub_strategy: checkpoint
hub_token:

saves_per_epoch: 2
warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
eval_max_new_tokens: 128
max_steps: -1
debug:
deepspeed:
weight_decay: 0.01
fsdp:
fsdp_config:

# Monitoring settings
wandb_watch: gradients # Track gradients
log_every_n_steps: 25 # More frequent logging
eval_every_n_steps: 100 # Regular evaluation
save_every_n_steps: 500 # Checkpoint frequency

# Performance monitoring
track_memory: true
track_cuda_memory: true
track_cuda_utilization: true
